### ISSUE TITLE
DataSet Edit - Rename Table Name

### ISSUE THREAD

**Issue by silzila** [silzila/pysilzila#26]
In Dataset edit page, when I try to rename a table name, it is asking in pop-up that if I really want to rename. This is unnecessary.
A desired behaviour is: after clicking rename, it should go to name edit mode with the existing name pre-populated & selected in it. (just like how renaming in tile or tab name).

Make sure when user doesn't give anything or just gives blank spaces, we should give warning  "at least one letter should be provided" in pop-up 

Also check inn Dataset Create page.

**Comment by sarvanrb** [comment]
Also, once rename button is clicked, there is no option to cancel it. having a esc / cancel option would be good.

**Comment by sarvanrb** [comment]
This bug is fixed in the above pull request #25
